stages:
  - test
  - deploy

.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'

.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        cov = process_folder()
        display(map(x -> (x.filename, get_summary(x)), cov))
        println()
        c, t = get_summary(cov)
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
  artifacts:
    paths:
      - "**/*.cov"

unittest-Julia 1.7:
  image: johannesflake/oscar
  stage: test
  extends:
    - .script
    - .coverage

doctest:
  image: johannesflake/oscar
  stage: test
  script:
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using PBWDeformations
        include("docs/make.jl")'
  artifacts:
    paths:
      - docs/build
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - doctest
  script:
    - mkdir -p public
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - master
