stages:
  - test
  - deploy

.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'

.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'

unittest-Julia 1.6:
  image: julia:1.6
  stage: test
  extends:
    - .script
    - .coverage

doctest:
  image: julia:1.6
  stage: test
  script:
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using PBWDeformations
        doctest(PBWDeformations)
        include("docs/make.jl")'
  artifacts:
    paths:
      - docs/build

pages:
  stage: deploy
  dependencies:
    - doctest
  script:
    - mkdir -p public
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - master
