name = "PBWDeformations"
uuid = "5e7992ee-18b2-4301-9ba0-4f17696dc75a"
authors = ["Johannes Flake <flake@art.rwth-aachen.de>", "Lars Göttgens <lars.goettgens@rwth-aachen.de>", "Phil Pützstück <phil.puetzstueck@rwth-aachen.de>"]
version = "0.1.0"

[compat]
julia = "1.6"
