name = "PBWDeformations"
uuid = "5e7992ee-18b2-4301-9ba0-4f17696dc75a"
authors = ["Lars Göttgens <lars.goettgens@rwth-aachen.de>", "Johannes Flake <flake@art.rwth-aachen.de>"]
version = "0.4.0-DEV"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "~1.0.3, ~1.1"
julia = "1.8"
