name = "PBWDeformations"
uuid = "5e7992ee-18b2-4301-9ba0-4f17696dc75a"
authors = ["Johannes Flake <flake@art.rwth-aachen.de>", "Lars Göttgens <lars.goettgens@rwth-aachen.de>", "Phil Pützstück <phil.puetzstueck@rwth-aachen.de>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Combinatorics = "1.0.0"
Oscar = "~0.6.0"
julia = "1.6"
