name = "PBWDeformations"
uuid = "5e7992ee-18b2-4301-9ba0-4f17696dc75a"
authors = ["Johannes Flake <flake@art.rwth-aachen.de>", "Lars Göttgens <lars.goettgens@rwth-aachen.de>"]
version = "0.3.0-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AbstractAlgebra = "0.29.2, 0.30"
Hecke = "0.18.9"
Oscar = "0.12"
julia = "1.6"
