name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'

      - name: Restore cache
        uses: julia-actions/cache@v1
        with:
          cache-name: 'docs-1.9'

      - name: "Dev Oscar.jl master"
        shell: julia --project=. --color=yes {0}
        run: |
          using Pkg
          Pkg.add(url="https://github.com/lgoettgens/Oscar.jl", rev="master-pbwdeformations")
        env:
          JULIA_PKG_PRECOMPILE_AUTO: no

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Install dependencies
        shell: julia --project=docs/ --color=yes {0}
        run: |
          using Pkg
          Pkg.add(url="https://github.com/lgoettgens/Oscar.jl", rev="master-pbwdeformations")
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ --color=yes docs/make.jl
